export const GOD_ACTION_TYPES = [
  "CREATE_GOD",
  "CREATE_ITEM", "SPAWN_ITEM", "SPAWN_PREDATOR", "KILL_PREDATOR",
  "DIV_HEAL_FROG", "DIV_SMITE_ENEMY", "DIV_SPAWN_ITEM", "DIV_SPAWN_PREDATOR",
  "GOD_PAN", "DIV_UPDATE_LAIR", "DIV_PLACE_LAIR",
] as const;
export type GodActionType = (typeof GOD_ACTION_TYPES)[number];
